version: '3.8'

volumes:
  elasticdata:
    driver: local

services:
  elasticsearch:
    container_name: labrosnertech_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      #xpack.monitoring.enabled: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - elasticdata:/usr/share/elasticsearch/data  #Monte o volume no caminho desejado
      - /etc/localtime:/etc/localtime:ro #esse volume é para sincronizar o horário do servidor fisico com o container

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: labrosnertech_kibana
    
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro #esse volume é para sincronizar o horário do servidor fisico com o container
    depends_on:
      - elasticsearch